disabled_rules:
  - identifier_name
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - first_where
  - last_where
  - implicit_return
  - identical_operands
  - modifier_order
  - nimble_operator
  - sorted_imports
  - toggle_bool
  - weak_delegate
  - empty_string
  - empty_count
included:
  - Sources
